apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miaya-data
  namespace: miaya-playbook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: <set to your default RWO class if needed>
