apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holm-content-pvc
  namespace: holm-community
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holm-data-pvc
  namespace: holm-community
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
