"""The phone tree. Order = priority of calling sequence."""

CONTACTS = [
    {
        "key": "guidance_center",
        "name": "The Guidance Center (Flagstaff)",
        "phone": "(928) 527-1899",
        "alt_phone": "1-877-756-4090 (24/7 crisis)",
        "purpose": "Confirm Miaya is admitted. Get her current status. Ask about visitation, family-contact policy, discharge plan, treating provider.",
        "address": "2187 N. Vickey St, Flagstaff, AZ 86004",
        "url": "https://tgcaz.org/",
        "priority": 1,
        "category": "Facility",
    },
    {
        "key": "coconino_sheriff",
        "name": "Coconino County Sheriff (inmate inquiry)",
        "phone": "(928) 226-5200",
        "purpose": "Confirm whether Miaya was booked. Get booking date, charges, current custody status.",
        "url": "https://www.coconino.az.gov/164/Sheriff",
        "priority": 1,
        "category": "Court / law enforcement",
    },
    {
        "key": "coconino_clerk",
        "name": "Coconino County Clerk of Superior Court",
        "phone": "(928) 679-7600",
        "purpose": "Get case number, next hearing date, attorney of record.",
        "address": "200 N San Francisco St, Flagstaff",
        "url": "https://www.coconino.az.gov/162/Superior-Court",
        "priority": 1,
        "category": "Court / law enforcement",
    },
    {
        "key": "mhc",
        "name": "Coconino County Mental Health Court",
        "phone": "(928) 679-7580",
        "purpose": "Diversion eligibility. Judge Joshua Steinlage, Division VII. SMI required. 14+ month program. Charges dismissed on completion.",
        "url": "https://www.coconino.az.gov/2964/Mental-Health-Court",
        "priority": 2,
        "category": "Court / law enforcement",
    },
    {
        "key": "swbh_smi",
        "name": "Southwest Behavioral — SMI Determination",
        "phone": "(855) 832-2866",
        "purpose": "Start the ~10-day SMI designation clock. Required for MHC eligibility.",
        "address": "1633 S Plaza Way, Flagstaff",
        "url": "https://www.sbhservices.org/",
        "priority": 2,
        "category": "Behavioral health",
    },
    {
        "key": "care1st_az",
        "name": "Care1st / AZ Complete Health–Complete Care (RBHA)",
        "phone": "(866) 560-4042",
        "purpose": "AHCCCS behavioral health intake. Coconino regional behavioral health authority. Apply alongside SMI.",
        "url": "https://www.care1staz.com/",
        "priority": 2,
        "category": "Behavioral health",
    },
    {
        "key": "ahccs_ohr",
        "name": "AHCCCS Office of Human Rights (appeals)",
        "phone": "(800) 421-2142",
        "email": "OHRts@azahcccs.gov",
        "purpose": "If SMI denied — file appeal here. Decisions in 3–60 days.",
        "priority": 4,
        "category": "Behavioral health",
    },
    {
        "key": "dna_legal",
        "name": "DNA-People's Legal Services (free legal aid)",
        "phone": "(928) 774-0653",
        "alt_phone": "(833) 362-1102",
        "purpose": "Free legal aid intake (Coconino). Backup if no private counsel funded.",
        "address": "2323 E. Greenlaw Ln, Suite 1, Flagstaff",
        "priority": 2,
        "category": "Legal",
    },
    {
        "key": "coconino_pd",
        "name": "Coconino County Public Defender",
        "phone": "(928) 679-7700",
        "purpose": "Court-appointed criminal counsel. Already assigned if she had arraignment. Director: Jennifer Stock.",
        "address": "110 E Cherry Ave, Flagstaff",
        "url": "https://www.coconino.az.gov/287/Public-Defender",
        "priority": 2,
        "category": "Legal",
    },
    {
        "key": "griffen_stevens",
        "name": "Griffen & Stevens Law Firm (private)",
        "phone": "(928) 226-0165",
        "purpose": "Private criminal defense + Rule 11 + Mental Health Court diversion. Ryan Stevens — Certified Criminal Law Specialist.",
        "address": "609 N. Humphreys St, Flagstaff",
        "url": "https://www.flagstaff-lawyer.com/",
        "priority": 3,
        "category": "Legal",
    },
    {
        "key": "glazer_hammond",
        "name": "Glazer, Hammond & Smets (private)",
        "phone": "(928) 985-4167",
        "purpose": "Stephen Glazer — Board Certified Criminal Law Specialist. Alternative to Griffen & Stevens.",
        "url": "https://www.glazerhammond.com/",
        "priority": 3,
        "category": "Legal",
    },
    {
        "key": "coconino_probate",
        "name": "Coconino County Probate (guardianship)",
        "phone": "(928) 679-7600",
        "purpose": "Guardianship / conservatorship filing. ~$191 filing fee. 60–90 day timeline. Prefer mental-health POA if she can sign.",
        "address": "200 N San Francisco St, Flagstaff",
        "priority": 4,
        "category": "Legal",
    },
    {
        "key": "open_door",
        "name": "The Open Door — Tonia Tewell (CPG-aware advocate)",
        "phone": "(801) 386-1077",
        "alt_phone": "801-548-3492 (hotline)",
        "email": "help@holdingouthelp.org",
        "purpose": "Family advocate familiar with Centennial Park / fundamentalist-Mormon community context. Trauma-informed care.",
        "url": "https://theopendoor.us/",
        "priority": 3,
        "category": "Family advocacy",
    },
    {
        "key": "cherish_families",
        "name": "Cherish Families (Colorado City)",
        "phone": "(928) 875-0969",
        "purpose": "Crisis support, counseling, family services for CPG/FLDS community. 12,766+ therapy sessions delivered.",
        "address": "280 W Township Ave, Colorado City, AZ",
        "url": "https://cherishfamilies.org/",
        "priority": 3,
        "category": "Family advocacy",
    },
    {
        "key": "nami_flagstaff",
        "name": "NAMI Flagstaff (family support)",
        "phone": "(928) 214-2218",
        "email": "flagnami@gmail.com",
        "purpose": "Family support group Thursdays 5:30–7pm at Hope Community Church, 3700 N. Fanning Dr. Family-to-Family 8-week course.",
        "url": "http://nami-flagstaff.org/",
        "priority": 4,
        "category": "Family support (yours)",
    },
    {
        "key": "nami_helpline",
        "name": "NAMI Caregiver HelpLine",
        "phone": "1-800-950-6264",
        "purpose": "Press 4 for caregiver specialists. Or text 'Family' to 62640. Mon–Fri 8am–8pm AZ time.",
        "priority": 4,
        "category": "Family support (yours)",
    },
    {
        "key": "spilsbury",
        "name": "Spilsbury Mortuary (St. George) — family records",
        "phone": "(435) 673-2454",
        "alt_phone": "(435) 635-2212 (Hurricane)",
        "purpose": "Ask for Dorothy Richardson Knudson 2018 funeral program — lists all 14 children. Confirms Miaya's parentage if needed for SNT/probate.",
        "url": "https://www.spilsburymortuary.com/",
        "priority": 5,
        "category": "Records / genealogy",
    },
]

CATEGORIES = [
    "Facility",
    "Court / law enforcement",
    "Behavioral health",
    "Legal",
    "Family advocacy",
    "Family support (yours)",
    "Records / genealogy",
]

STATUSES = [
    "not_started",
    "attempted_no_answer",
    "voicemail_left",
    "reached_in_progress",
    "callback_scheduled",
    "completed",
    "blocked",
]

STATUS_LABELS = {
    "not_started": "🔘 Not started",
    "attempted_no_answer": "📵 No answer",
    "voicemail_left": "🎙️ Voicemail left",
    "reached_in_progress": "🟡 Reached — in progress",
    "callback_scheduled": "📅 Callback scheduled",
    "completed": "✅ Completed",
    "blocked": "🛑 Blocked",
}


def by_key(key: str) -> dict:
    for c in CONTACTS:
        if c["key"] == key:
            return c
    raise KeyError(key)


ASK_ALLEN_DEFAULT_ITEMS = [
    ("Residential placement (30 days, Sierra Tucson / Decision Point tier)", 60000.0, True),
    ("Private criminal defense retainer (Griffen & Stevens)", 20000.0, True),
    ("Third-party Special Needs Trust setup (Bivens & PLAN AZ)", 5000.0, True),
    ("Corporate SNT trustee — first year", 8000.0, True),
    ("Patient advocate / care navigator (3 months)", 6000.0, False),
    ("Mental health POA / limited guardianship legal fees", 2000.0, False),
    ("Family advocate retainer (Open Door / Cherish Families)", 3000.0, False),
    ("Travel reserve (family visits, hearings)", 5000.0, False),
    ("Contingency / SNT initial corpus", 25000.0, False),
]
